apiVersion: v1
kind: Service
metadata:
  name: karsajobs-backend-service
  labels:
    app: karsajobs
spec:
  selector:
    app: karsajobs
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
